/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bsc;

import static bsc.Setup.testConnection;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yitbarek
 */
public class ControlPanel extends javax.swing.JFrame {
    String Database_URL, Database_Username, Database_Password, Server_URL, DownloadPath;
    private DefaultTableModel model;
    DatabaseService dbService = new DatabaseService();
    Vector<String> comboBoxData = new Vector<>();
    String Search_UserName = "";
    
    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        tableview();
        loadConfigToFields();
    }
    
    private void tableview(){
        dbService.getUserValue(Registered_Users_Table, "");
        model = (DefaultTableModel) Registered_Users_Table.getModel();
        Registered_Users_Table.setRowHeight(30);
        Registered_Users_Table.setShowGrid(true);
        Registered_Users_Table.setGridColor(Color.black);
        Registered_Users_Table.setBackground(Color.white);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        ViewUsers_Pane = new javax.swing.JPanel();
        Registered_Users_Pane = new javax.swing.JScrollPane();
        Registered_Users_Table = new javax.swing.JTable();
        View_Users_Titlebar = new javax.swing.JLabel();
        Users_Pane = new javax.swing.JPanel();
        Functionality_Panel = new javax.swing.JPanel();
        Functionality_Titlebar = new javax.swing.JLabel();
        Search_Users_Button = new javax.swing.JButton();
        Add_Users_Button = new javax.swing.JButton();
        Add_Department_Button = new javax.swing.JButton();
        Add_Document_Type_Button = new javax.swing.JButton();
        Card_Panel = new javax.swing.JPanel();
        Landing = new javax.swing.JPanel();
        Landing_Notice = new javax.swing.JLabel();
        Add_Department_Panel = new javax.swing.JPanel();
        Department_Name_Field = new javax.swing.JTextField();
        Department_Name_Label = new javax.swing.JLabel();
        Department_Add_Button = new javax.swing.JButton();
        Department_Add_Result = new javax.swing.JLabel();
        Search_Users_Panel = new javax.swing.JPanel();
        User_Name_Label = new javax.swing.JLabel();
        User_Name_Field = new javax.swing.JTextField();
        Search_Button = new javax.swing.JButton();
        Delete_User_Button = new javax.swing.JButton();
        Reset_Password_Button = new javax.swing.JButton();
        Notice_Password_Reset = new javax.swing.JLabel();
        Search_Result_Scrollpane = new javax.swing.JScrollPane();
        Search_Result_Editor = new javax.swing.JEditorPane("text/html", "");
        New_Password_Field = new javax.swing.JTextField();
        New_Password_Label = new javax.swing.JLabel();
        Notice_Delete = new javax.swing.JLabel();
        Add_New_Users_Panel = new javax.swing.JPanel();
        First_Name_Label = new javax.swing.JLabel();
        First_Name_Field = new javax.swing.JTextField();
        Department_Label = new javax.swing.JLabel();
        String sql1 = "SELECT department FROM departments";
        try{
            DatabaseService a = new DatabaseService();
            try(Connection conn = a.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql1);)
            {
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String deps = rs.getString(1);
                    comboBoxData.add(deps);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Department_Combo = new javax.swing.JComboBox<>(comboBoxData);
        Is_Head = new javax.swing.JCheckBox();
        Password_Label = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        Register_Button = new javax.swing.JButton();
        tabela2 = new javax.swing.JLabel();
        tabela1 = new javax.swing.JLabel();
        Test_Setup_Pane = new javax.swing.JPanel();
        Database_Titlebar = new javax.swing.JLabel();
        D_URL_Lable = new javax.swing.JLabel();
        D_URL = new javax.swing.JTextField();
        D_Username_Lable = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        D_Password_Lable = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        D_Test_Button = new javax.swing.JButton();
        D_Test_Result = new javax.swing.JLabel();
        D_Setup_Button = new javax.swing.JButton();
        D_Setup_Result = new javax.swing.JLabel();
        Server_Panel = new javax.swing.JPanel();
        Server_Titlebar = new javax.swing.JLabel();
        S_URL_Label = new javax.swing.JLabel();
        S_URL = new javax.swing.JTextField();
        Local_Server_CheckBox = new javax.swing.JCheckBox();
        S_Add_Button = new javax.swing.JButton();
        S_Test_Button = new javax.swing.JButton();
        S_Test_Result = new javax.swing.JLabel();
        S_Download_Lable = new javax.swing.JLabel();
        S_DownloadPath_Label = new javax.swing.JLabel();
        S_Attach_Button = new javax.swing.JButton();
        S_Setup_Button = new javax.swing.JButton();
        S_Setup_Result = new javax.swing.JLabel();
        S_Saved_URL = new javax.swing.JLabel();
        S_Saved_DownloadPath = new javax.swing.JLabel();
        D_Saved_URL = new javax.swing.JLabel();
        D_Saved_Username = new javax.swing.JLabel();
        D_Saved_Password = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setBackground(new java.awt.Color(204, 255, 255));
        TabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ViewUsers_Pane.setBackground(new java.awt.Color(255, 255, 255));

        Registered_Users_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "username", "passsword", "department", "role"
            }
        ));
        Registered_Users_Pane.setViewportView(Registered_Users_Table);

        View_Users_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        View_Users_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        View_Users_Titlebar.setText("Registered users");

        javax.swing.GroupLayout ViewUsers_PaneLayout = new javax.swing.GroupLayout(ViewUsers_Pane);
        ViewUsers_Pane.setLayout(ViewUsers_PaneLayout);
        ViewUsers_PaneLayout.setHorizontalGroup(
            ViewUsers_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewUsers_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewUsers_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(View_Users_Titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addComponent(Registered_Users_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                .addContainerGap())
        );
        ViewUsers_PaneLayout.setVerticalGroup(
            ViewUsers_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewUsers_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(View_Users_Titlebar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registered_Users_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("view users", ViewUsers_Pane);

        Users_Pane.setBackground(new java.awt.Color(255, 255, 255));

        Functionality_Panel.setBackground(new java.awt.Color(255, 255, 255));

        Functionality_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Functionality_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Functionality_Titlebar.setText("Functionalities");

        Search_Users_Button.setBackground(new java.awt.Color(204, 255, 204));
        Search_Users_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Search_Users_Button.setText("Search user");
        Search_Users_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Users_ButtonActionPerformed(evt);
            }
        });

        Add_Users_Button.setBackground(new java.awt.Color(204, 255, 204));
        Add_Users_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Add_Users_Button.setText("Add new user");
        Add_Users_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Users_ButtonActionPerformed(evt);
            }
        });

        Add_Department_Button.setBackground(new java.awt.Color(204, 255, 204));
        Add_Department_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Add_Department_Button.setText("Add Departments");
        Add_Department_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Department_ButtonActionPerformed(evt);
            }
        });

        Add_Document_Type_Button.setBackground(new java.awt.Color(204, 255, 204));
        Add_Document_Type_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Add_Document_Type_Button.setText("Add Document Types");
        Add_Document_Type_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Document_Type_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Functionality_PanelLayout = new javax.swing.GroupLayout(Functionality_Panel);
        Functionality_Panel.setLayout(Functionality_PanelLayout);
        Functionality_PanelLayout.setHorizontalGroup(
            Functionality_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Functionality_PanelLayout.createSequentialGroup()
                .addGroup(Functionality_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Functionality_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Functionality_Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Functionality_PanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(Functionality_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Search_Users_Button)
                            .addComponent(Add_Users_Button)
                            .addComponent(Add_Department_Button)
                            .addComponent(Add_Document_Type_Button))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Functionality_PanelLayout.setVerticalGroup(
            Functionality_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Functionality_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Functionality_Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add_Users_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_Users_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Add_Department_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Add_Document_Type_Button)
                .addContainerGap())
        );

        Card_Panel.setLayout(new java.awt.CardLayout());

        Landing_Notice.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Landing_Notice.setText("Chose any functions");

        javax.swing.GroupLayout LandingLayout = new javax.swing.GroupLayout(Landing);
        Landing.setLayout(LandingLayout);
        LandingLayout.setHorizontalGroup(
            LandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LandingLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(Landing_Notice)
                .addGap(74, 74, 74))
        );
        LandingLayout.setVerticalGroup(
            LandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LandingLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(Landing_Notice)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        Card_Panel.add(Landing, "card4");

        Department_Name_Label.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Department_Name_Label.setText("Department Name");

        Department_Add_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Department_Add_Button.setText("Add");

        Department_Add_Result.setText("---");

        javax.swing.GroupLayout Add_Department_PanelLayout = new javax.swing.GroupLayout(Add_Department_Panel);
        Add_Department_Panel.setLayout(Add_Department_PanelLayout);
        Add_Department_PanelLayout.setHorizontalGroup(
            Add_Department_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Department_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Department_Name_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_Department_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Department_Add_Button)
                    .addComponent(Department_Name_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(Department_Add_Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Add_Department_PanelLayout.setVerticalGroup(
            Add_Department_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Department_PanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Add_Department_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department_Name_Label)
                    .addComponent(Department_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Department_Add_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Department_Add_Result)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        Card_Panel.add(Add_Department_Panel, "card6");

        User_Name_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        User_Name_Label.setText("username :");

        Search_Button.setBackground(new java.awt.Color(0, 0, 255));
        Search_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_Button.setForeground(new java.awt.Color(255, 255, 255));
        Search_Button.setText("Search");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        Delete_User_Button.setBackground(new java.awt.Color(255, 204, 204));
        Delete_User_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Delete_User_Button.setText("Delete user");
        Delete_User_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_ButtonActionPerformed(evt);
            }
        });

        Reset_Password_Button.setBackground(new java.awt.Color(255, 204, 204));
        Reset_Password_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Reset_Password_Button.setText("Reset user password");
        Reset_Password_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_Password_ButtonActionPerformed(evt);
            }
        });

        Notice_Password_Reset.setText("--");

        Search_Result_Editor.setContentType("text/html");
        Search_Result_Scrollpane.setViewportView(Search_Result_Editor);

        New_Password_Label.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        New_Password_Label.setText("New password:");

        Notice_Delete.setText("---");

        javax.swing.GroupLayout Search_Users_PanelLayout = new javax.swing.GroupLayout(Search_Users_Panel);
        Search_Users_Panel.setLayout(Search_Users_PanelLayout);
        Search_Users_PanelLayout.setHorizontalGroup(
            Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_Users_PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Search_Users_PanelLayout.createSequentialGroup()
                        .addComponent(User_Name_Label)
                        .addGap(13, 13, 13)
                        .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Search_Users_PanelLayout.createSequentialGroup()
                                .addComponent(User_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Search_Users_PanelLayout.createSequentialGroup()
                                    .addComponent(Delete_User_Button)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Notice_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(Search_Result_Scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Search_Users_PanelLayout.createSequentialGroup()
                        .addComponent(New_Password_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(New_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Notice_Password_Reset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reset_Password_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Search_Users_PanelLayout.setVerticalGroup(
            Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_Users_PanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(User_Name_Label)
                    .addComponent(User_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_Result_Scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_User_Button)
                    .addComponent(Notice_Delete))
                .addGap(18, 18, 18)
                .addGroup(Search_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(New_Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reset_Password_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Notice_Password_Reset)
                .addGap(19, 19, 19))
        );

        //Add_New_Users_Panel.setVisible(false);

        Card_Panel.add(Search_Users_Panel, "card3");

        First_Name_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        First_Name_Label.setText("firstname :");

        Department_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Department_Label.setText("department :");

        Is_Head.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Is_Head.setText("head");
        Is_Head.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Is_HeadActionPerformed(evt);
            }
        });

        Password_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password_Label.setText("password :");

        Register_Button.setBackground(new java.awt.Color(0, 0, 255));
        Register_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register");
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });

        tabela2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabela2.setText("--");

        tabela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabela1.setText("--");

        javax.swing.GroupLayout Add_New_Users_PanelLayout = new javax.swing.GroupLayout(Add_New_Users_Panel);
        Add_New_Users_Panel.setLayout(Add_New_Users_PanelLayout);
        Add_New_Users_PanelLayout.setHorizontalGroup(
            Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_New_Users_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabela2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Add_New_Users_PanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(First_Name_Label)
                            .addComponent(Department_Label)
                            .addComponent(Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Register_Button)
                            .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Is_Head)
                            .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(First_Name_Field, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Department_Combo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addComponent(tabela1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Add_New_Users_PanelLayout.setVerticalGroup(
            Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_New_Users_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(First_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department_Label)
                    .addComponent(Department_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Is_Head)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_New_Users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label)
                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Register_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabela1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabela2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //Add_New_Users_Panel.setVisible(false);
        Card_Panel.add(Add_New_Users_Panel, "card5");

        javax.swing.GroupLayout Users_PaneLayout = new javax.swing.GroupLayout(Users_Pane);
        Users_Pane.setLayout(Users_PaneLayout);
        Users_PaneLayout.setHorizontalGroup(
            Users_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Users_PaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Functionality_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Card_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        Users_PaneLayout.setVerticalGroup(
            Users_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Users_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Users_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Functionality_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        TabbedPane.addTab("add users", Users_Pane);

        Test_Setup_Pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Database_Titlebar.setBackground(new java.awt.Color(51, 255, 102));
        Database_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Database_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Database_Titlebar.setText("Database Setup");
        Test_Setup_Pane.add(Database_Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 276, -1));

        D_URL_Lable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        D_URL_Lable.setText("URL :");
        Test_Setup_Pane.add(D_URL_Lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 36, -1, -1));
        Test_Setup_Pane.add(D_URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 36, 233, -1));

        D_Username_Lable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        D_Username_Lable.setText("Username :");
        Test_Setup_Pane.add(D_Username_Lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, -1, -1));
        Test_Setup_Pane.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 94, 201, -1));

        D_Password_Lable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        D_Password_Lable.setText("Password :");
        Test_Setup_Pane.add(D_Password_Lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, -1, -1));
        Test_Setup_Pane.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 152, 199, -1));

        D_Test_Button.setBackground(new java.awt.Color(0, 0, 0));
        D_Test_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        D_Test_Button.setForeground(new java.awt.Color(255, 255, 255));
        D_Test_Button.setText("Test");
        D_Test_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_Test_ButtonActionPerformed(evt);
            }
        });
        Test_Setup_Pane.add(D_Test_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 210, -1, -1));

        D_Test_Result.setText("---");
        Test_Setup_Pane.add(D_Test_Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 213, 121, -1));

        D_Setup_Button.setBackground(new java.awt.Color(255, 0, 102));
        D_Setup_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        D_Setup_Button.setText("Finish Setup");
        D_Setup_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_Setup_ButtonActionPerformed(evt);
            }
        });
        Test_Setup_Pane.add(D_Setup_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 239, -1, -1));

        D_Setup_Result.setText("---");
        Test_Setup_Pane.add(D_Setup_Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 268, 173, -1));

        Server_Panel.setBackground(new java.awt.Color(204, 255, 204));

        Server_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Server_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Server_Titlebar.setText("Server Setup");

        S_URL_Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        S_URL_Label.setText("URL :");

        Local_Server_CheckBox.setBackground(new java.awt.Color(255, 255, 255));
        Local_Server_CheckBox.setText("Local Server");
        Local_Server_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Local_Server_CheckBoxActionPerformed(evt);
            }
        });

        S_Add_Button.setBackground(new java.awt.Color(0, 0, 153));
        S_Add_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        S_Add_Button.setForeground(new java.awt.Color(255, 255, 255));
        S_Add_Button.setText("Add");
        S_Add_Button.setBorder(null);
        S_Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_Add_ButtonActionPerformed(evt);
            }
        });

        S_Test_Button.setBackground(new java.awt.Color(0, 0, 0));
        S_Test_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        S_Test_Button.setForeground(new java.awt.Color(255, 255, 255));
        S_Test_Button.setText("Test");
        S_Test_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_Test_ButtonActionPerformed(evt);
            }
        });

        S_Test_Result.setText("---");

        S_Download_Lable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        S_Download_Lable.setText("File Download Path :");

        S_DownloadPath_Label.setText("---");

        S_Attach_Button.setBackground(new java.awt.Color(0, 0, 153));
        S_Attach_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        S_Attach_Button.setForeground(new java.awt.Color(255, 255, 255));
        S_Attach_Button.setText("Browse");
        S_Attach_Button.setBorder(null);
        S_Attach_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_Attach_ButtonActionPerformed(evt);
            }
        });

        S_Setup_Button.setBackground(new java.awt.Color(255, 0, 102));
        S_Setup_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        S_Setup_Button.setText("Finish Setup");
        S_Setup_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_Setup_ButtonActionPerformed(evt);
            }
        });

        S_Setup_Result.setText("---");

        S_Saved_URL.setText("NaN");

        S_Saved_DownloadPath.setText("NaN");

        javax.swing.GroupLayout Server_PanelLayout = new javax.swing.GroupLayout(Server_Panel);
        Server_Panel.setLayout(Server_PanelLayout);
        Server_PanelLayout.setHorizontalGroup(
            Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Server_PanelLayout.createSequentialGroup()
                .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Server_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Server_PanelLayout.createSequentialGroup()
                                .addComponent(S_Download_Lable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(S_Attach_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(S_DownloadPath_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Server_PanelLayout.createSequentialGroup()
                                .addComponent(S_URL_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(S_Saved_URL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(Server_PanelLayout.createSequentialGroup()
                                            .addComponent(S_Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(S_Test_Button)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(S_Test_Result, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                                    .addGroup(Server_PanelLayout.createSequentialGroup()
                                        .addComponent(S_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Local_Server_CheckBox))))
                            .addGroup(Server_PanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(S_Saved_DownloadPath, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Server_PanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(S_Setup_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(S_Setup_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(Server_Titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Server_PanelLayout.setVerticalGroup(
            Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Server_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Server_Titlebar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Local_Server_CheckBox)
                    .addComponent(S_URL_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_Saved_URL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S_Test_Button)
                    .addComponent(S_Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S_Test_Result))
                .addGap(30, 30, 30)
                .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Server_PanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(S_Download_Lable))
                    .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(S_Attach_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(S_DownloadPath_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_Saved_DownloadPath)
                .addGap(18, 18, 18)
                .addGroup(Server_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S_Setup_Button)
                    .addComponent(S_Setup_Result))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Test_Setup_Pane.add(Server_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 6, -1, -1));

        D_Saved_URL.setText("NaN");
        Test_Setup_Pane.add(D_Saved_URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 60, 233, -1));

        D_Saved_Username.setText("NaN");
        Test_Setup_Pane.add(D_Saved_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 118, 190, -1));

        D_Saved_Password.setText("NaN");
        Test_Setup_Pane.add(D_Saved_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 176, 190, -1));

        TabbedPane.addTab("test & setup", Test_Setup_Pane);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UoG Office Solution Suit - Admin Panel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_Users_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Users_ButtonActionPerformed
        CardLayout cl = (CardLayout) (Card_Panel.getLayout());
        cl.show(Card_Panel, "card3");
    }//GEN-LAST:event_Search_Users_ButtonActionPerformed

    private void Add_Users_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Users_ButtonActionPerformed
        CardLayout cl = (CardLayout) (Card_Panel.getLayout());
        cl.show(Card_Panel, "card5");
    }//GEN-LAST:event_Add_Users_ButtonActionPerformed

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        Search_UserName = User_Name_Field.getText().trim();
        try {
            String[] userInfo = dbService.searchUser(Search_UserName);
            if (userInfo != null) {
                Search_Result_Editor.setText(
                            "<html>" +
                             "<b><font color='green'>[*] Found! [*] </font></b>" + "<br>"  +
                             "<b><font color='purple'>Username:</font></b> " + userInfo[0] + "<br>" +
                             "<b><font color='purple'>Role:</font></b> " + userInfo[1] + "<br>" +
                             "<b><font color='purple'>Department:</font></b> " + userInfo[2] +
                             "</html>"
                        );
            } else {
                Search_Result_Editor.setText("<html><b><font color='red'>User not found!</font></b></html>");
            }
        } catch (Exception ex) {
             Search_Result_Editor.setText("<html><font color='red'>Error!</font></html>");
        }
    }//GEN-LAST:event_Search_ButtonActionPerformed

    private void Delete_User_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_ButtonActionPerformed
        String username = User_Name_Field.getText().trim();
        if (username.isEmpty()) {
            Notice_Delete.setText("<html><font color='red'>Enter username to delete.</font></html>");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete user: " + username + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                 boolean archived = dbService.archiveUser(username);
                if (archived) {
                    Notice_Delete.setText("<html><font color='green'>Deleted!</font></html>");
                } else {
                    Notice_Delete.setText("<html><font color='red'>Failed to delete!</font></html>");
                }
            } catch (Exception ex) {
                Notice_Delete.setText("<html><font color='red'>Error!</font></html>");
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_Delete_User_ButtonActionPerformed

    private void Is_HeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Is_HeadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Is_HeadActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
        String firstName = First_Name_Field.getText().trim();
        String department = (String) Department_Combo.getSelectedItem();
        String password = new String(Password_Field.getPassword());
        boolean isChecked = Is_Head.isSelected();
        String departmentAbbrev = null;
        
        try {
            departmentAbbrev = dbService.getAbbreviation(department);
        } catch (Exception ex) {
            Logger.getLogger(ControlPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        String username = firstName + "@" + departmentAbbrev;

            DatabaseService x = new DatabaseService();
        try {
            if (isChecked) {
                if (x.signup(department, username, Supporter.hashPassword(password), "head") &&
                    x.signupMessages(department, username)) {
                    tabela1.setText("<html><b><font color='green'>SUCCESSFULLY REGISTERED</font></b></html>");
                    tabela2.setText("Your username is " + username);
                    tableview();
                } else {
                    tabela1.setText("<html><b><font color='green'>PROBLEM ENCOUNTERED!</font></b></html>");
                    tabela2.setText("Remember: One account per user only!");
                }
            } else if (!isChecked) {
                if (x.signup(department, username, Supporter.hashPassword(password), "user") &&
                    x.signupMessages(department, username)) {
                    tabela1.setText("<html><b><font color='green'>SUCCESSFULLY REGISTERED</font></b></html>");
                    tabela2.setText("Your username is " + username);
                    tableview();
                } else {
                    tabela1.setText("<html><b><font color='green'>PROBLEM ENCOUNTERED!</font></b></html>");
                    tabela2.setText("Remember: One account per user only!");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ControlPanel.class.getName()).log(Level.SEVERE, null, ex);
            tabela1.setText("Error occurred!");
            tabela2.setText(ex.getMessage());
        }

    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void D_Setup_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_Setup_ButtonActionPerformed
        Database_URL = D_URL.getText();
        Database_Username = Username.getText();
        Database_Password = Password.getText();

        if(Supporter.saveConfig(Database_URL, Database_Username, Database_Password, null, null))
        {
            D_Setup_Result.setText("SAVED!");
            D_Setup_Result.setForeground(Color.GREEN); 
            D_Setup_Result.setFont(D_Setup_Result.getFont().deriveFont(Font.BOLD));
            loadConfigToFields();
        }
        else{
            D_Setup_Result.setText("Failed!");
            D_Setup_Result.setForeground(Color.RED); 
            D_Setup_Result.setFont(D_Setup_Result.getFont().deriveFont(Font.BOLD));
        }
    }//GEN-LAST:event_D_Setup_ButtonActionPerformed

    private void S_Setup_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_Setup_ButtonActionPerformed
        Server_URL = S_URL.getText();
        DownloadPath = S_DownloadPath_Label.getText();

        if(Supporter.saveConfig(null, null, null, Server_URL, DownloadPath))
        {
            S_Setup_Result.setText("Success!");
            loadConfigToFields();
        }
        else{
            S_Setup_Result.setText("Failed!");
        }
    }//GEN-LAST:event_S_Setup_ButtonActionPerformed

    private void S_Attach_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_Attach_ButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Only allow folders
        int option = fileChooser.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fileChooser.getSelectedFile();
            S_DownloadPath_Label.setText(selectedFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_S_Attach_ButtonActionPerformed

    private void S_Test_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_Test_ButtonActionPerformed
String serverAddress = null;
String input = S_URL.getText().trim();

try {
    if (input.startsWith("http://") || input.startsWith("https://")) {
        String[] parts = input.split("/");
        if (parts.length >= 3) {
            serverAddress = parts[2];
        }
    } else if (input.startsWith("\\\\") || input.startsWith("//")) {
        String withoutSlashes = input.replace("\\\\", "").replace("//", "");
        String[] parts = withoutSlashes.split("\\\\|/");
        if (parts.length >= 1) {
            serverAddress = parts[0];
        }
    } else {
        serverAddress = input;
    }

    if (serverAddress != null && Supporter.testServer(serverAddress, 445) && Supporter.testNetworkPath(input)) {
        S_Test_Result.setText("Successful!");
        S_Test_Result.setForeground(Color.GREEN);
    } else {
        S_Test_Result.setText("Error!");
        S_Test_Result.setForeground(Color.RED);
    }
    S_Test_Result.setFont(S_Test_Result.getFont().deriveFont(Font.BOLD));

} catch (Exception e) {
    S_Test_Result.setText("Exception!");
    S_Test_Result.setForeground(Color.RED);
}
    }//GEN-LAST:event_S_Test_ButtonActionPerformed

    private void S_Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_Add_ButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Only allow folders
        int option = fileChooser.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fileChooser.getSelectedFile();
            S_URL.setText(selectedFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_S_Add_ButtonActionPerformed

    private void Local_Server_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Local_Server_CheckBoxActionPerformed
        if (Local_Server_CheckBox.isSelected()) {
            S_URL.setText("");
            S_URL.setEnabled(false);
            S_Add_Button.setEnabled(true);
            S_Test_Button.setEnabled(false);
        } else {
            S_URL.setEnabled(true);
            S_Add_Button.setEnabled(false);
            S_Test_Button.setEnabled(true);
        }
    }//GEN-LAST:event_Local_Server_CheckBoxActionPerformed

    private void D_Test_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_Test_ButtonActionPerformed
      Database_URL = D_URL.getText();
      Database_Username = Username.getText();
      Database_Password = Password.getText();   
      
      if(testConnection(Database_URL, Database_Username, Database_Password)){
      D_Test_Result.setText("Successful!");
      D_Test_Result.setForeground(Color.GREEN); 
      D_Test_Result.setFont(D_Test_Result.getFont().deriveFont(Font.BOLD));}
      else{
      D_Test_Result.setText("Error!");
      D_Test_Result.setForeground(Color.RED); 
      D_Test_Result.setFont(D_Test_Result.getFont().deriveFont(Font.BOLD));}
    }//GEN-LAST:event_D_Test_ButtonActionPerformed

    private void Add_Department_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Department_ButtonActionPerformed
        String deptName = JOptionPane.showInputDialog(
            null,
            "Enter new department name:",
            "Add Department",
            JOptionPane.PLAIN_MESSAGE
        );
        if (deptName == null) {
            return;
        }
        deptName = deptName.trim();
        if (deptName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Department name cannot be empty.");
            return;
        }
        try {
            boolean added = dbService.addDepartment(deptName);
            if (added) {
                JOptionPane.showMessageDialog(null, "Department added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Department already exists.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_Add_Department_ButtonActionPerformed

    private void Add_Document_Type_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Document_Type_ButtonActionPerformed
        String docType = JOptionPane.showInputDialog(
            null,
            "Enter new Document Type:",
            "Add Document Type",
            JOptionPane.PLAIN_MESSAGE
        );
        if (docType == null) {
            return; 
        }
        docType = docType.trim();
        if (docType.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Document type cannot be empty.");
            return;
        }
        try {
            boolean added = dbService.addDocType(docType);
            if (added) {
                JOptionPane.showMessageDialog(null, "Document type added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Document type already exists.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_Add_Document_Type_ButtonActionPerformed

    private void Reset_Password_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_Password_ButtonActionPerformed
        String new_pass = New_Password_Field.getText();

        if (Search_UserName.isEmpty() || new_pass.isEmpty()) {
            Notice_Password_Reset.setText("Please enter both username and new password.");
            return;
        }
        try {
            boolean success = dbService.resetUserPassword(Search_UserName, Supporter.hashPassword(new_pass));
            if (success) {
                Notice_Password_Reset.setText("<html><b><font color='green'>Password Reseted!</font></b></html>");
            } else {
                Notice_Password_Reset.setText("<html><b><font color='red'>Password Reset Failed!</font></b></html>");
            }
        } catch (Exception ex) {
            Notice_Password_Reset.setText("<html><b><font color='red'>Error!</font></b></html>");
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_Reset_Password_ButtonActionPerformed

    
    private void loadConfigToFields() {
    Properties props = Supporter.loadConfig();
    D_Saved_URL.setText(props.getProperty("database.url", ""));
    D_Saved_Username.setText(props.getProperty("database.username", ""));
    D_Saved_Password.setText(props.getProperty("database.password", ""));
    S_Saved_URL.setText(props.getProperty("server.url", ""));
    S_Saved_DownloadPath.setText(props.getProperty("download.path", ""));
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Department_Button;
    private javax.swing.JPanel Add_Department_Panel;
    private javax.swing.JButton Add_Document_Type_Button;
    private javax.swing.JPanel Add_New_Users_Panel;
    private javax.swing.JButton Add_Users_Button;
    private javax.swing.JPanel Card_Panel;
    private javax.swing.JLabel D_Password_Lable;
    private javax.swing.JLabel D_Saved_Password;
    private javax.swing.JLabel D_Saved_URL;
    private javax.swing.JLabel D_Saved_Username;
    private javax.swing.JButton D_Setup_Button;
    private javax.swing.JLabel D_Setup_Result;
    private javax.swing.JButton D_Test_Button;
    private javax.swing.JLabel D_Test_Result;
    private javax.swing.JTextField D_URL;
    private javax.swing.JLabel D_URL_Lable;
    private javax.swing.JLabel D_Username_Lable;
    private javax.swing.JLabel Database_Titlebar;
    private javax.swing.JButton Delete_User_Button;
    private javax.swing.JButton Department_Add_Button;
    private javax.swing.JLabel Department_Add_Result;
    private javax.swing.JComboBox<String> Department_Combo;
    private javax.swing.JLabel Department_Label;
    private javax.swing.JTextField Department_Name_Field;
    private javax.swing.JLabel Department_Name_Label;
    private javax.swing.JTextField First_Name_Field;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JPanel Functionality_Panel;
    private javax.swing.JLabel Functionality_Titlebar;
    private javax.swing.JCheckBox Is_Head;
    private javax.swing.JPanel Landing;
    private javax.swing.JLabel Landing_Notice;
    private javax.swing.JCheckBox Local_Server_CheckBox;
    private javax.swing.JTextField New_Password_Field;
    private javax.swing.JLabel New_Password_Label;
    private javax.swing.JLabel Notice_Delete;
    private javax.swing.JLabel Notice_Password_Reset;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JButton Register_Button;
    private javax.swing.JScrollPane Registered_Users_Pane;
    private javax.swing.JTable Registered_Users_Table;
    private javax.swing.JButton Reset_Password_Button;
    private javax.swing.JButton S_Add_Button;
    private javax.swing.JButton S_Attach_Button;
    private javax.swing.JLabel S_DownloadPath_Label;
    private javax.swing.JLabel S_Download_Lable;
    private javax.swing.JLabel S_Saved_DownloadPath;
    private javax.swing.JLabel S_Saved_URL;
    private javax.swing.JButton S_Setup_Button;
    private javax.swing.JLabel S_Setup_Result;
    private javax.swing.JButton S_Test_Button;
    private javax.swing.JLabel S_Test_Result;
    private javax.swing.JTextField S_URL;
    private javax.swing.JLabel S_URL_Label;
    private javax.swing.JButton Search_Button;
    private javax.swing.JEditorPane Search_Result_Editor;
    private javax.swing.JScrollPane Search_Result_Scrollpane;
    private javax.swing.JButton Search_Users_Button;
    private javax.swing.JPanel Search_Users_Panel;
    private javax.swing.JPanel Server_Panel;
    private javax.swing.JLabel Server_Titlebar;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel Test_Setup_Pane;
    private javax.swing.JTextField User_Name_Field;
    private javax.swing.JLabel User_Name_Label;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel Users_Pane;
    private javax.swing.JPanel ViewUsers_Pane;
    private javax.swing.JLabel View_Users_Titlebar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tabela1;
    private javax.swing.JLabel tabela2;
    // End of variables declaration//GEN-END:variables
}
