package bsc;


import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yitbarek
 */
public class Landing extends javax.swing.JFrame {
    Set<Integer> seenMessages = new HashSet<>();
     String username, role, dep, Request_File_Path, Check_File_Path, Check_File_Name;
     Message selectedMessage;
     File pdfFile_Name;
     Vector<String> comboBoxData = new Vector<>();
     Vector<String> DT_comboBoxData = new Vector<>();
     Vector<String> To_Department_Combo_Data = new Vector<>();
     DatabaseService dbService = new DatabaseService();
     Supporter a = new Supporter();
     List<String> User_Detail;
     DefaultListModel<Message> listModel;
     

    /**
     * Creates new form Landing
     * @param username
     */
    public Landing(String username) {
        this.username = username;
        initComponents();   
        users(username);
        setLocationRelativeTo(null);
    }
    
public void users(String username){
    DatabaseService b = new DatabaseService();
    User_Detail = b.userDetail(username);
    role = User_Detail.get(0);
    dep = User_Detail.get(1);
                       
    if (role.equals("user")) {
        Role.setText("USER");
        MD_Reject_Button.setVisible(false);
        MD_Approve_Button.setVisible(false);
        }
     else if (role.equals("head")) {
        Role.setText("HEAD");}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Username_Label = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        App_Name = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        Request_Digital_Stamp_Panel = new javax.swing.JPanel();
        Digital_Stamp_Titlebar = new javax.swing.JLabel();
        To_Label = new javax.swing.JLabel();
        String sql1 = "SELECT department FROM departments";
        try{
            DatabaseService a = new DatabaseService();
            try(Connection conn = a.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql1);)
            {
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String deps = rs.getString(1);
                    comboBoxData.add(deps);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        To_Department_Combo = new javax.swing.JComboBox<>(comboBoxData);
        DS_Document_Type_Label = new javax.swing.JLabel();
        Upload_Label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AttachBtn = new javax.swing.JButton();
        RequestButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestFilePath_Field = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        RequestNote = new javax.swing.JTextArea();
        String sqln = "SELECT documentType FROM doctypes";
        try{
            DatabaseService a = new DatabaseService();
            try(Connection conn = a.getConnection();
                PreparedStatement pst = conn.prepareStatement(sqln);)
            {
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String deps = rs.getString(1);
                    DT_comboBoxData.add(deps);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Document_Type_Combo = new javax.swing.JComboBox<>(DT_comboBoxData);
        Inbox_Panel = new javax.swing.JPanel();
        Inbox_Titlebar = new javax.swing.JLabel();
        Inbox_ScrollPane = new javax.swing.JScrollPane();
        DatabaseService b = new DatabaseService();
        User_Detail = b.userDetail(username);
        String role = User_Detail.get(0);
        String dep = User_Detail.get(1);

        //DefaultListModel<Message> listModel;
        listModel = new javax.swing.DefaultListModel<Message>();
        Inbox = new javax.swing.JList<Message>(listModel);
        messageTextArea = new javax.swing.JTextField();
        sendMessageButton = new javax.swing.JButton();
        To_Label1 = new javax.swing.JLabel();
        String sqlz = "SELECT department FROM departments";
        try{
            DatabaseService a = new DatabaseService();
            try(Connection conn = a.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql1);)
            {
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String deps = rs.getString(1);
                    To_Department_Combo_Data.add(deps);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        To_Department_Combo_Inbox = new javax.swing.JComboBox<>(To_Department_Combo_Data);
        Message_Detail_Panel = new javax.swing.JPanel();
        Message_Request_Titlebar = new javax.swing.JLabel();
        MD_Timestamp_Label = new javax.swing.JLabel();
        MD_Timestamp_Detail = new javax.swing.JLabel();
        MD_From_Label = new javax.swing.JLabel();
        MD_From_Detail = new javax.swing.JLabel();
        MD_To_Label = new javax.swing.JLabel();
        MD_To_Detail = new javax.swing.JLabel();
        MD_Document_Type_Label = new javax.swing.JLabel();
        MD_Document_Type_Detail = new javax.swing.JLabel();
        MD_Filename_Label = new javax.swing.JLabel();
        MD_Filename_Detail = new javax.swing.JLabel();
        MD_Preview_Button = new javax.swing.JButton();
        MD_Note_Label = new javax.swing.JLabel();
        MD_Note_Detail = new javax.swing.JScrollPane();
        MD_Note_Area = new javax.swing.JTextArea();
        MD_Reject_Button = new javax.swing.JButton();
        MD_Approve_Button = new javax.swing.JButton();
        Check_Authentic_Document_Panel = new javax.swing.JPanel();
        Check_Authentic_Document_Titlebar = new javax.swing.JLabel();
        Filename_Label = new javax.swing.JLabel();
        CheckFileName_Label = new javax.swing.JLabel();
        Filepath_Label = new javax.swing.JLabel();
        Filepath_ScrollPane = new javax.swing.JScrollPane();
        Filepath_Area = new javax.swing.JTextArea();
        CAD_Attach_Button = new javax.swing.JButton();
        Check_AD_Button = new javax.swing.JButton();
        Document_Type_Label = new javax.swing.JLabel();
        Document_Type_Result = new javax.swing.JLabel();
        Description_ScrollPane = new javax.swing.JScrollPane();
        Description_Area = new javax.swing.JTextArea();
        Description_Label = new javax.swing.JLabel();
        Verdict_Label = new javax.swing.JLabel();
        signout_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOSS");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        Username_Label.setBackground(new java.awt.Color(204, 204, 204));
        Username_Label.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Username_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username_Label.setText("Welcome, "+username);

        Header.setBackground(new java.awt.Color(255, 255, 255));

        App_Name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        App_Name.setForeground(new java.awt.Color(0, 0, 153));
        App_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        App_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uog.jpg"))); // NOI18N
        App_Name.setText("UoG Office Solution Suit");

        Role.setBackground(new java.awt.Color(255, 255, 255));
        Role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Role.setForeground(new java.awt.Color(102, 0, 102));
        Role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Role.setText("---");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(App_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(App_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Role, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Request_Digital_Stamp_Panel.setBackground(new java.awt.Color(255, 255, 255));

        Digital_Stamp_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Digital_Stamp_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Digital_Stamp_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stamp.png"))); // NOI18N
        Digital_Stamp_Titlebar.setText("Digital Stamp");

        To_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        To_Label.setText("To :");

        To_Department_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_Department_ComboActionPerformed(evt);
            }
        });

        DS_Document_Type_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        DS_Document_Type_Label.setText("Document Type :");

        Upload_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Upload_Label.setText("Upload :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Note :");

        AttachBtn.setBackground(new java.awt.Color(0, 0, 255));
        AttachBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AttachBtn.setForeground(new java.awt.Color(255, 255, 255));
        AttachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach.png"))); // NOI18N
        AttachBtn.setText("Attach");
        AttachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachBtnActionPerformed(evt);
            }
        });

        RequestButton.setBackground(new java.awt.Color(255, 0, 0));
        RequestButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RequestButton.setForeground(new java.awt.Color(255, 255, 255));
        RequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/request.png"))); // NOI18N
        RequestButton.setText("Request");
        RequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButtonActionPerformed(evt);
            }
        });

        RequestFilePath_Field.setEditable(false);
        RequestFilePath_Field.setColumns(20);
        RequestFilePath_Field.setLineWrap(true);
        RequestFilePath_Field.setRows(5);
        RequestFilePath_Field.setWrapStyleWord(true);
        jScrollPane1.setViewportView(RequestFilePath_Field);

        RequestNote.setColumns(20);
        RequestNote.setRows(5);
        jScrollPane3.setViewportView(RequestNote);

        Document_Type_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Document_Type_ComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Request_Digital_Stamp_PanelLayout = new javax.swing.GroupLayout(Request_Digital_Stamp_Panel);
        Request_Digital_Stamp_Panel.setLayout(Request_Digital_Stamp_PanelLayout);
        Request_Digital_Stamp_PanelLayout.setHorizontalGroup(
            Request_Digital_Stamp_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Request_Digital_Stamp_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Digital_Stamp_Titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Request_Digital_Stamp_PanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Request_Digital_Stamp_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Request_Digital_Stamp_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AttachBtn)
                        .addComponent(RequestButton)
                        .addComponent(To_Label)
                        .addComponent(jLabel8)
                        .addComponent(Upload_Label)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addComponent(To_Department_Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Document_Type_Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DS_Document_Type_Label)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        Request_Digital_Stamp_PanelLayout.setVerticalGroup(
            Request_Digital_Stamp_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Request_Digital_Stamp_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Digital_Stamp_Titlebar)
                .addGap(18, 18, 18)
                .addComponent(To_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(To_Department_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DS_Document_Type_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Document_Type_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Upload_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AttachBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RequestButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Inbox_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Inbox_Panel.setEnabled(false);

        Inbox_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Inbox_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inbox_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inbox.png"))); // NOI18N
        Inbox_Titlebar.setText("Inbox");

        Inbox.setCellRenderer(new MessageCellRenderer());
        Inbox.setModel(listModel);
        Supporter c = new Supporter();
        Timer timer = new Timer(5000, e -> {
            Message selectedValue = Inbox.getSelectedValue();
            try{
                List<Message> newMessages = b.fetchMessages(role, username, dep);
                boolean hasUnreadMessages = false;

                if (newMessages != null) {
                    for (Message message : newMessages) {

                        if (!seenMessages.contains(message.getMessageId())) {
                            seenMessages.add(message.getMessageId());
                            if (!message.isRead()) {
                                hasUnreadMessages = true;
                            }

                            listModel.add(0, message);
                        }
                    }

                    if (hasUnreadMessages) {
                        c.playNotificationSound();
                    }
                }

                if (selectedValue != null && listModel.contains(selectedValue)) {
                    Inbox.setSelectedValue(selectedValue, true);
                }
            }
            catch (Exception exe) {
            }

        });

        timer.start();
        Inbox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Inbox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                InboxValueChanged(evt);
            }
        });
        Inbox.setFixedCellHeight(20);
        Inbox_ScrollPane.setViewportView(Inbox);

        sendMessageButton.setBackground(new java.awt.Color(0, 0, 204));
        sendMessageButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        sendMessageButton.setForeground(new java.awt.Color(255, 255, 255));
        sendMessageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broadcast.png"))); // NOI18N
        sendMessageButton.setText("Send");
        sendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtonActionPerformed(evt);
            }
        });

        To_Label1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        To_Label1.setText("Broadcast To :");

        To_Department_Combo_Inbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_Department_Combo_InboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inbox_PanelLayout = new javax.swing.GroupLayout(Inbox_Panel);
        Inbox_Panel.setLayout(Inbox_PanelLayout);
        Inbox_PanelLayout.setHorizontalGroup(
            Inbox_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inbox_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inbox_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inbox_Titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inbox_ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Inbox_PanelLayout.createSequentialGroup()
                        .addGroup(Inbox_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Inbox_PanelLayout.createSequentialGroup()
                                .addComponent(To_Label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(To_Department_Combo_Inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Inbox_PanelLayout.createSequentialGroup()
                                .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendMessageButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Inbox_PanelLayout.setVerticalGroup(
            Inbox_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inbox_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inbox_Titlebar)
                .addGap(1, 1, 1)
                .addComponent(Inbox_ScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Inbox_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To_Department_Combo_Inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(To_Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Inbox_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageTextArea)
                    .addComponent(sendMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Message_Detail_Panel.setBackground(new java.awt.Color(255, 255, 255));

        Message_Request_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Message_Request_Titlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Message_Request_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        Message_Request_Titlebar.setText("Messages & Requests");

        MD_Timestamp_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MD_Timestamp_Label.setText("Time Stamp  :");

        MD_Timestamp_Detail.setBackground(new java.awt.Color(255, 255, 255));
        MD_Timestamp_Detail.setText("---");

        MD_From_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MD_From_Label.setText("From  :");

        MD_From_Detail.setBackground(new java.awt.Color(255, 255, 255));
        MD_From_Detail.setText("---");

        MD_To_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MD_To_Label.setText("To  :");

        MD_To_Detail.setBackground(new java.awt.Color(255, 255, 255));
        MD_To_Detail.setText("---");

        MD_Document_Type_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MD_Document_Type_Label.setText("Document Type  :");

        MD_Document_Type_Detail.setBackground(new java.awt.Color(255, 255, 255));
        MD_Document_Type_Detail.setText("---");

        MD_Filename_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MD_Filename_Label.setText("File :");

        MD_Filename_Detail.setBackground(new java.awt.Color(255, 255, 255));
        MD_Filename_Detail.setText("---");

        MD_Preview_Button.setBackground(new java.awt.Color(0, 0, 255));
        MD_Preview_Button.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MD_Preview_Button.setForeground(new java.awt.Color(255, 255, 255));
        MD_Preview_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        MD_Preview_Button.setText("Preview");
        MD_Preview_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_Preview_ButtonActionPerformed(evt);
            }
        });

        MD_Note_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        MD_Note_Label.setText("Note :");

        MD_Note_Area.setEditable(false);
        MD_Note_Area.setColumns(20);
        MD_Note_Area.setLineWrap(true);
        MD_Note_Area.setRows(5);
        MD_Note_Area.setWrapStyleWord(true);
        MD_Note_Detail.setViewportView(MD_Note_Area);

        MD_Reject_Button.setBackground(new java.awt.Color(204, 0, 0));
        MD_Reject_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MD_Reject_Button.setForeground(new java.awt.Color(255, 255, 255));
        MD_Reject_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
        MD_Reject_Button.setText("Reject");
        MD_Reject_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_Reject_ButtonActionPerformed(evt);
            }
        });

        MD_Approve_Button.setBackground(new java.awt.Color(0, 153, 0));
        MD_Approve_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        MD_Approve_Button.setForeground(new java.awt.Color(255, 255, 255));
        MD_Approve_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/like.png"))); // NOI18N
        MD_Approve_Button.setText("Approve");
        MD_Approve_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_Approve_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Message_Detail_PanelLayout = new javax.swing.GroupLayout(Message_Detail_Panel);
        Message_Detail_Panel.setLayout(Message_Detail_PanelLayout);
        Message_Detail_PanelLayout.setHorizontalGroup(
            Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                        .addComponent(Message_Request_Titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                                .addComponent(MD_Timestamp_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MD_Timestamp_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                                        .addComponent(MD_From_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MD_From_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                                        .addComponent(MD_To_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MD_To_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                                        .addComponent(MD_Document_Type_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MD_Document_Type_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(30, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Message_Detail_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                        .addComponent(MD_Filename_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MD_Filename_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(MD_Approve_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MD_Reject_Button))))
                    .addComponent(MD_Note_Label)
                    .addComponent(MD_Note_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(MD_Preview_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Message_Detail_PanelLayout.setVerticalGroup(
            Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Message_Detail_PanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Message_Request_Titlebar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MD_Timestamp_Label)
                    .addComponent(MD_Timestamp_Detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MD_From_Label)
                    .addComponent(MD_From_Detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MD_To_Label)
                    .addComponent(MD_To_Detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MD_Document_Type_Label)
                    .addComponent(MD_Document_Type_Detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MD_Filename_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MD_Filename_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MD_Preview_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MD_Note_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MD_Note_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Message_Detail_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MD_Reject_Button)
                    .addComponent(MD_Approve_Button))
                .addGap(47, 47, 47))
        );

        Check_Authentic_Document_Panel.setBackground(new java.awt.Color(255, 255, 255));

        Check_Authentic_Document_Titlebar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Check_Authentic_Document_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        Check_Authentic_Document_Titlebar.setText("Check Authentic Document");

        Filename_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Filename_Label.setText("File Name :");

        CheckFileName_Label.setBackground(new java.awt.Color(255, 255, 255));
        CheckFileName_Label.setText("---");

        Filepath_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Filepath_Label.setText("File Path :");

        Filepath_Area.setEditable(false);
        Filepath_Area.setColumns(20);
        Filepath_Area.setLineWrap(true);
        Filepath_Area.setRows(5);
        Filepath_Area.setWrapStyleWord(true);
        Filepath_ScrollPane.setViewportView(Filepath_Area);

        CAD_Attach_Button.setBackground(new java.awt.Color(0, 0, 255));
        CAD_Attach_Button.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        CAD_Attach_Button.setForeground(new java.awt.Color(255, 255, 255));
        CAD_Attach_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach.png"))); // NOI18N
        CAD_Attach_Button.setText("Attach");
        CAD_Attach_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAD_Attach_ButtonActionPerformed(evt);
            }
        });

        Check_AD_Button.setBackground(new java.awt.Color(204, 0, 0));
        Check_AD_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Check_AD_Button.setForeground(new java.awt.Color(255, 255, 255));
        Check_AD_Button.setText("Check");
        Check_AD_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_AD_ButtonActionPerformed(evt);
            }
        });

        Document_Type_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Document_Type_Label.setText("Document Type:");

        Document_Type_Result.setText("---");

        Description_Area.setColumns(20);
        Description_Area.setLineWrap(true);
        Description_Area.setRows(5);
        Description_Area.setWrapStyleWord(true);
        Description_ScrollPane.setViewportView(Description_Area);

        Description_Label.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Description_Label.setText("Description :");

        Verdict_Label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Verdict_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Verdict_Label.setText("---");

        javax.swing.GroupLayout Check_Authentic_Document_PanelLayout = new javax.swing.GroupLayout(Check_Authentic_Document_Panel);
        Check_Authentic_Document_Panel.setLayout(Check_Authentic_Document_PanelLayout);
        Check_Authentic_Document_PanelLayout.setHorizontalGroup(
            Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_Authentic_Document_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Check_Authentic_Document_PanelLayout.createSequentialGroup()
                        .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Check_Authentic_Document_Titlebar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Check_Authentic_Document_PanelLayout.createSequentialGroup()
                                .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Filepath_Label)
                                    .addGroup(Check_Authentic_Document_PanelLayout.createSequentialGroup()
                                        .addComponent(Filename_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckFileName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Verdict_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(Check_Authentic_Document_PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Description_Label)
                            .addGroup(Check_Authentic_Document_PanelLayout.createSequentialGroup()
                                .addComponent(CAD_Attach_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check_AD_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Filepath_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(Description_ScrollPane)
                            .addGroup(Check_Authentic_Document_PanelLayout.createSequentialGroup()
                                .addComponent(Document_Type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Document_Type_Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Check_Authentic_Document_PanelLayout.setVerticalGroup(
            Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_Authentic_Document_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Check_Authentic_Document_Titlebar)
                .addGap(20, 20, 20)
                .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Filename_Label)
                    .addComponent(CheckFileName_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Filepath_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Filepath_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CAD_Attach_Button)
                    .addComponent(Check_AD_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Check_Authentic_Document_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Document_Type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Document_Type_Result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Description_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Verdict_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        signout_Button.setBackground(new java.awt.Color(0, 0, 204));
        signout_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signout_Button.setForeground(new java.awt.Color(255, 255, 255));
        signout_Button.setText("Log Out");
        signout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Request_Digital_Stamp_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signout_Button)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Inbox_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Message_Detail_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Check_Authentic_Document_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username_Label)
                    .addComponent(signout_Button))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Message_Detail_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inbox_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Check_Authentic_Document_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Request_Digital_Stamp_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachBtnActionPerformed
        
 if (evt.getSource() == AttachBtn) {
    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter pdfFilter = new FileNameExtensionFilter("PDF Files", "pdf");
    fileChooser.setFileFilter(pdfFilter);
    int res = fileChooser.showOpenDialog(null); 
    if (res == JFileChooser.APPROVE_OPTION) {
        File Request_file = fileChooser.getSelectedFile();
        Request_File_Path = Request_file.getAbsolutePath();
        RequestFilePath_Field.setText(Request_File_Path);
    }
}

    }//GEN-LAST:event_AttachBtnActionPerformed

    private void RequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButtonActionPerformed
    String department = (String) To_Department_Combo.getSelectedItem();
    String doc_type = (String) Document_Type_Combo.getSelectedItem();
    String note = RequestNote.getText();
    boolean requestSuccess;
    
         try {
                System.out.println(Request_File_Path);
                a.uploadFiles(Request_File_Path);
                requestSuccess = dbService.sendRequest(doc_type, Request_File_Path, username, department, note, "Request");
                if (requestSuccess) {
                JOptionPane.showMessageDialog(this, "Request sent successfully!");} 
                else {
            JOptionPane.showMessageDialog(this, "Failed to send request.");}   
             } 
         catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error sending request: " + e.getMessage());
    }

    }//GEN-LAST:event_RequestButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void MD_Preview_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_Preview_ButtonActionPerformed
     boolean success = a.downloadANDopenPDF(pdfFile_Name.getName());
       if(success){}
       else{JOptionPane.showMessageDialog(this, "Document not found on server / File format error");}
    }//GEN-LAST:event_MD_Preview_ButtonActionPerformed

    private void MD_Reject_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_Reject_ButtonActionPerformed
        String RejectedMessage = "Document is rejected by " + username;
        try {
            dbService.saveMessage(selectedMessage.getFile_Type(), pdfFile_Name.getName(),"broadcast",username, selectedMessage.getToDept(), RejectedMessage);
            JOptionPane.showMessageDialog(this, "Document Rejected!");
              } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        }
    }//GEN-LAST:event_MD_Reject_ButtonActionPerformed

    private void MD_Approve_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_Approve_ButtonActionPerformed
        String stampText = "Approved by " + username + " on " +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        String AppprovedMessage = "Document have been approved and digitally stamped by " + username;

        try {      
            String x = a.addDigitalStamp(pdfFile_Name.getName(), stampText, selectedMessage.getFile_Type());  
            if(x!=null){
             dbService.saveMessage(selectedMessage.getFile_Type(), x, "broadcast", username, dbService.DeptFetcher(selectedMessage.getUsername()), AppprovedMessage);
             JOptionPane.showMessageDialog(this, "Document Approved!");}
            else{
                JOptionPane.showMessageDialog(this, "Document not found in server");}   
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        } 
    }//GEN-LAST:event_MD_Approve_ButtonActionPerformed

    private void sendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtonActionPerformed
        String message = messageTextArea.getText().trim();
        String recipient = (String) To_Department_Combo_Inbox.getSelectedItem();
        
    if (!message.isEmpty() && recipient!=null) {
        try {
            dbService.saveMessage("NULL", "NULL", "broadcast", username, recipient, message);
            messageTextArea.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Recipient/Message cannot be empty.");
    }
       
    }//GEN-LAST:event_sendMessageButtonActionPerformed

    private void signout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_ButtonActionPerformed
        this.setVisible(false); 
        dispose();
        UserLogin log = new UserLogin();
        log.setVisible(true);
    }//GEN-LAST:event_signout_ButtonActionPerformed

    private void CAD_Attach_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAD_Attach_ButtonActionPerformed
if (evt.getSource() == CAD_Attach_Button) {
    
    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter pdfFilter = new FileNameExtensionFilter("PDF Files", "pdf");
    fileChooser.setFileFilter(pdfFilter);
    int res = fileChooser.showOpenDialog(null);
    if (res == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        Check_File_Path = file.getAbsolutePath();
        Check_File_Name = file.getName();
        Filepath_Area.setText(Check_File_Path);
        CheckFileName_Label.setText(Check_File_Name);
    }
}   
    }//GEN-LAST:event_CAD_Attach_ButtonActionPerformed

    private void To_Department_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_Department_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_To_Department_ComboActionPerformed

    private void InboxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_InboxValueChanged
        if (!evt.getValueIsAdjusting()) {
            selectedMessage = Inbox.getSelectedValue();
            
            if (selectedMessage == null) {
                return;
            }
                       
        try {
                dbService.markMessagesAsRead(selectedMessage.getMessageId(),username);
                List<Message> newMessages = dbService.fetchMessages(role, username, dep);
                boolean hasUnreadMessages = false;
                Message selectedValue = Inbox.getSelectedValue();

            if (newMessages != null) {
                
            for (Message message : newMessages) {

            if (!seenMessages.contains(message.getMessageId())) {
                seenMessages.add(message.getMessageId());
                
                if (!message.isRead()) {
                    hasUnreadMessages = true;
                }
                listModel.add(0, message);
            }
        }

        if (hasUnreadMessages) {
            a.playNotificationSound();
        }
    }
    
    if (selectedValue != null && listModel.contains(selectedValue)) {
        Inbox.setSelectedValue(selectedValue, true);
    }
            selectedMessage.setRead(true);
            Inbox.repaint();
            }
        catch (Exception ex) {
                Logger.getLogger(Landing.class.getName()).log(Level.SEVERE, null, ex);
            }              
            
            MD_Timestamp_Detail.setText(selectedMessage.getTS());
            MD_Note_Area.setText(selectedMessage.getContent());
            MD_To_Detail.setText(selectedMessage.getToDept());
            MD_From_Detail.setText(selectedMessage.getUsername());
            MD_Document_Type_Detail.setText(selectedMessage.getFile_Type());
            
            Request_File_Path = selectedMessage.getFile();
            pdfFile_Name = new File(Request_File_Path);
            MD_Filename_Detail.setText(pdfFile_Name.getName()); 
        }       
    }//GEN-LAST:event_InboxValueChanged


    private void Check_AD_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_AD_ButtonActionPerformed
        boolean isIntact = a.checkFileIntegrity(Check_File_Path);
        if(isIntact){
            Verdict_Label.setText("MATCH FOUND! / AUTHENTIC!");
            Document_Type_Result.setText(selectedMessage.getFile_Type());
            Description_Area.setText("Hash calculated for file: "+ Check_File_Name + " => Hash: "
              + a.calculateFileHash(Check_File_Path)  );
        }
        else{
            Description_Area.setText("Hash calculated for file: "+ Check_File_Name + " => Hash: "
              + a.calculateFileHash(Check_File_Path)  );
            Document_Type_Result.setText(selectedMessage.getFile_Type());
            Verdict_Label.setText("NOT MATCH FOUND! / FRAUD!");
        }
    }//GEN-LAST:event_Check_AD_ButtonActionPerformed

    private void Document_Type_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Document_Type_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Document_Type_ComboActionPerformed

    private void To_Department_Combo_InboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_Department_Combo_InboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_To_Department_Combo_InboxActionPerformed


    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    // Set the Nimbus look and feel
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Create and display the form
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            String username = "YourUsername"; // Replace with actual username
            new Landing(username).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel App_Name;
    private javax.swing.JButton AttachBtn;
    private javax.swing.JButton CAD_Attach_Button;
    private javax.swing.JLabel CheckFileName_Label;
    private javax.swing.JButton Check_AD_Button;
    private javax.swing.JPanel Check_Authentic_Document_Panel;
    private javax.swing.JLabel Check_Authentic_Document_Titlebar;
    private javax.swing.JLabel DS_Document_Type_Label;
    private javax.swing.JTextArea Description_Area;
    private javax.swing.JLabel Description_Label;
    private javax.swing.JScrollPane Description_ScrollPane;
    private javax.swing.JLabel Digital_Stamp_Titlebar;
    private javax.swing.JComboBox<String> Document_Type_Combo;
    private javax.swing.JLabel Document_Type_Label;
    private javax.swing.JLabel Document_Type_Result;
    private javax.swing.JLabel Filename_Label;
    private javax.swing.JTextArea Filepath_Area;
    private javax.swing.JLabel Filepath_Label;
    private javax.swing.JScrollPane Filepath_ScrollPane;
    private javax.swing.JPanel Header;
    public javax.swing.JList<Message> Inbox;
    private javax.swing.JPanel Inbox_Panel;
    private javax.swing.JScrollPane Inbox_ScrollPane;
    private javax.swing.JLabel Inbox_Titlebar;
    private javax.swing.JButton MD_Approve_Button;
    private javax.swing.JLabel MD_Document_Type_Detail;
    private javax.swing.JLabel MD_Document_Type_Label;
    private javax.swing.JLabel MD_Filename_Detail;
    private javax.swing.JLabel MD_Filename_Label;
    private javax.swing.JLabel MD_From_Detail;
    private javax.swing.JLabel MD_From_Label;
    private javax.swing.JTextArea MD_Note_Area;
    private javax.swing.JScrollPane MD_Note_Detail;
    private javax.swing.JLabel MD_Note_Label;
    private javax.swing.JButton MD_Preview_Button;
    private javax.swing.JButton MD_Reject_Button;
    private javax.swing.JLabel MD_Timestamp_Detail;
    private javax.swing.JLabel MD_Timestamp_Label;
    private javax.swing.JLabel MD_To_Detail;
    private javax.swing.JLabel MD_To_Label;
    private javax.swing.JPanel Message_Detail_Panel;
    private javax.swing.JLabel Message_Request_Titlebar;
    private javax.swing.JButton RequestButton;
    private javax.swing.JTextArea RequestFilePath_Field;
    private javax.swing.JTextArea RequestNote;
    private javax.swing.JPanel Request_Digital_Stamp_Panel;
    private javax.swing.JLabel Role;
    private javax.swing.JComboBox<String> To_Department_Combo;
    private javax.swing.JComboBox<String> To_Department_Combo_Inbox;
    private javax.swing.JLabel To_Label;
    private javax.swing.JLabel To_Label1;
    private javax.swing.JLabel Upload_Label;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JLabel Verdict_Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField messageTextArea;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JButton signout_Button;
    // End of variables declaration//GEN-END:variables
}
