package bsc;

import java.sql.*;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author Yitbarek
 */
public class Login extends javax.swing.JFrame {
    private static final Preferences prefs = Preferences.userNodeForPackage(Login.class);
    private String savedUsername;

    /**
     * Creates new form landing
     */
    public Login() {
        loadUsername();
        initComponents();
        LoginError.setVisible(false);
        setLocationRelativeTo(null);
    }
    private void saveUsername(String username) {
        prefs.put("username", username);
    }
        private void loadUsername() {
        savedUsername = prefs.get("username", "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Page_Panel = new javax.swing.JPanel();
        App_Name_Label = new javax.swing.JLabel();
        Username_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField(savedUsername);
        LoginButton = new javax.swing.JButton();
        Office_Name_Label = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();
        saveUsernameCheckBox = new javax.swing.JCheckBox();
        Setup_redirect = new javax.swing.JButton();
        LoginError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOHA Office Solution Suit");
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        Login_Page_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Login_Page_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        App_Name_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        App_Name_Label.setForeground(new java.awt.Color(0, 0, 153));
        App_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        App_Name_Label.setText("UoG Office Solution Suit");
        Login_Page_Panel.add(App_Name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 390, -1));

        Username_Label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Username_Label.setText("Username :");
        Login_Page_Panel.add(Username_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 22));

        Password_Label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Password_Label.setText("Password :");
        Login_Page_Panel.add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, -1, -1));

        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFieldMouseClicked(evt);
            }
        });
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        Login_Page_Panel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 80, 176, -1));

        LoginButton.setBackground(new java.awt.Color(0, 0, 204));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setLabel("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Login_Page_Panel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 138, 85, -1));

        Office_Name_Label.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Office_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Office_Name_Label.setText("Fasildes Campus");
        Login_Page_Panel.add(Office_Name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 390, 25));

        ResetButton.setBackground(new java.awt.Color(255, 0, 0));
        ResetButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        Login_Page_Panel.add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 138, 85, -1));
        Login_Page_Panel.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 110, 176, -1));

        saveUsernameCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        saveUsernameCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        saveUsernameCheckBox.setText("Save username for next time");
        saveUsernameCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveUsernameCheckBox.setSelected(!savedUsername.isEmpty());
        boolean isUsernameSaved = !savedUsername.isEmpty();
        saveUsernameCheckBox.setSelected(isUsernameSaved);
        usernameField.setEditable(!isUsernameSaved);
        saveUsernameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUsernameCheckBoxActionPerformed(evt);
            }
        });
        Login_Page_Panel.add(saveUsernameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 199, 384, -1));

        Setup_redirect.setBackground(new java.awt.Color(255, 204, 204));
        Setup_redirect.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Setup_redirect.setText("click here to SetUp");
        Setup_redirect.setBorder(null);
        Setup_redirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Setup_redirectActionPerformed(evt);
            }
        });
        Login_Page_Panel.add(Setup_redirect, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 243, -1, -1));

        LoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        LoginError.setText("Invalid username/password combination!");
        Login_Page_Panel.add(LoginError, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 167, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login_Page_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login_Page_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
                                            
    DatabaseService dbService = new DatabaseService();
    String username = usernameField.getText();
    String password = passField.getText();
    
    String sql0 = "SELECT EmpPass FROM login WHERE EmpUserName = ?";
    
    try (Connection conn = dbService.getConnection();
         PreparedStatement stm = conn.prepareStatement(sql0)) {
        
        stm.setString(1, username);
        try (ResultSet rs = stm.executeQuery()) {
            if (rs.next()) {
                String storedHashedPassword = rs.getString("EmpPass");
                boolean isMatch = Supporter.validatePassword(password, storedHashedPassword);
                if (isMatch) {
                    dispose(); 
                    Landing hpage = new Landing(username);
                    hpage.setVisible(true); 
                    if (saveUsernameCheckBox.isSelected()) {
                        saveUsername(username);
                    }
                } else {
                    LoginError.setVisible(true);
                    passField.setText("");
                }
            } else {
                LoginError.setVisible(true);
                passField.setText("");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage());
    }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        usernameField.setText("");
        passField.setText("");
        saveUsernameCheckBox.setSelected(false);
        usernameField.setEditable(true);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void saveUsernameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUsernameCheckBoxActionPerformed
        usernameField.setEditable(!saveUsernameCheckBox.isSelected());
    }//GEN-LAST:event_saveUsernameCheckBoxActionPerformed

    private void usernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseClicked
         if (!usernameField.isEditable()) {
            usernameField.transferFocus();
        }
    }//GEN-LAST:event_usernameFieldMouseClicked

    private void Setup_redirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Setup_redirectActionPerformed
        int result = JOptionPane.showConfirmDialog(this, 
    "Are you sure you want to reset to default configuration?", 
    "Confirm Reset", 
    JOptionPane.YES_NO_OPTION);

if (result != JOptionPane.YES_OPTION) return;

        //dispose();  
        Setup setup_frame = new Setup();
        setup_frame.show();
    }//GEN-LAST:event_Setup_redirectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel App_Name_Label;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginError;
    private javax.swing.JPanel Login_Page_Panel;
    private javax.swing.JLabel Office_Name_Label;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton Setup_redirect;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JPasswordField passField;
    private javax.swing.JCheckBox saveUsernameCheckBox;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
